# Generated by Django 4.1.1 on 2022-09-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='coin type')),
                ('value', models.IntegerField(verbose_name='coin value')),
                ('num', models.IntegerField(verbose_name='Number of coins')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='product name')),
                ('value', models.FloatField(verbose_name='Price value')),
                ('num', models.IntegerField(verbose_name='Number of products')),
            ],
        ),
    ]
